# Generated by Django 3.1.4 on 2023-03-15 03:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='default-profile_dor4jw.png', max_length=255, verbose_name='avatar'),
        ),
    ]
